/** True when data was generated by xterm as a reply to a terminal query. */
export function isTerminalProtocolResponse(data: string): boolean {
  return /^\x1b\[(?:[?>=][0-9;]*c|\??[0-9;]*n|\??[0-9]+;[0-9]+R|\?[0-9]+;[0-9]+\$y)$/.test(data)
    || /^\x1b\](?:4;[0-9]+;|1[012];).+(?:\x07|\x1b\\)$/.test(data)
}
