/** True when data is a reply generated by a terminal emulator for a PTY query. */
export function isTerminalProtocolResponse(data: string): boolean {
  return /^\x1b\[(?:[?>=][0-9;]*c|\??[0-9;]*n|\??[0-9]+;[0-9]+R|\?[0-9]+;[0-9]+\$y)$/.test(data)
    || /^\x1b\](?:4;[0-9]+;|1[012];).+(?:\x07|\x1b\\)$/.test(data)
}

/** True for the required Primary Device Attributes reply to a DA1 query. */
export function isPrimaryDeviceAttributesResponse(data: string): boolean {
  return /^\x1b\[\?[0-9;]*c$/.test(data)
}
